set -g default-shell /bin/zsh
set-option -sa terminal-overrides  ",xterm*:Tc"
# set -g default-terminal "xterm-256color"
set -g default-terminal "screen-256color"
set -sg escape-time 10

set -g mouse on

# Shift Alt vim keys to switch windows
# bind -n M-H previous-window
# bind -n M-L next-window

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Binds for resize-pane
bind-key -r -T prefix M-Up resize-pane -U 10
bind-key -r -T prefix M-Down resize-pane -D 10
bind-key -r -T prefix M-Left resize-pane -L 10
bind-key -r -T prefix M-Right resize-pane -R 10
bind-key -r -T prefix C-Up resize-pane -U 10
bind-key -r -T prefix C-Down resize-pane -D 10
bind-key -r -T prefix C-Left resize-pane -L 10
bind-key -r -T prefix C-Right resize-pane -R 10

# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Configs for dreams of code catppuccin theme
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_tabs_enabled off

set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W" # use "#W" for application instead of directory

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
